import Head from "next/head";
import Footer from "../../components/ui/Footer";
import Header from "../../components/ui/Header";
import api from "../../services/api";
import { Button } from "../../components/forms/Button";

export async function getServerSideProps(ctx) {
  const slug = ctx.params.slug;
  const response = await api.get(`/movie/${slug}`);

  return {
    props: {
      movie: response.data,
    },
  };
}

export default function SingleMovie({ movie }) {
  console.log(movie);
  return (
    <main className="tw-bg-darkPurple tw-h-[100vh] tw-w-full tw-relative">
      <Head>
        <title>Laon Productions - Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="tw-w-full tw-px-[5%] tw-flex tw-justify-between tw-mt-[40px]">
        <div className="tw-w-[20%]">
          <div>
            <img src={movie.movie_data.cover_image} />
          </div>
          <a href={movie.movie_data.link_trailer} target="_blank">
            <Button content="ASSISTIR TRAILER" />
          </a>
        </div>
        <div className="tw-w-[70%] ">
          <div>
            <h1 className="tw-text-[30px] tw-text-white">
              {movie.movie_data.title}
            </h1>
            <h3 className="tw-text-lightPink tw-font-light">
              <span className="tw-font-bold">Título original:</span>{" "}
              {movie.movie_data.original_title}
            </h3>
            <h3 className="tw-text-lightPink tw-font-light">
              <span className="tw-font-bold">Ano:</span>{" "}
              {movie.movie_data.release_year}
            </h3>
            <h3 className="tw-text-lightPink tw-font-light">
              <span className="tw-font-bold">Duração:</span>{" "}
              {movie.movie_data.duration}
            </h3>
            <div className="tw-flex tw-mt-[10px]">
              {movie.categories.map((category, i) => (
                <div
                  key={i}
                  className="tw-border-[1px] tw-border-lightPurple tw-text-white tw-px-[30px] tw-py-[10px] tw-rounded-[30px] tw-mr-[10px]"
                >
                  <p>{category.category_title}</p>
                </div>
              ))}
            </div>
          </div>
          <div className="tw-mt-[50px]">
            <div className="tw-w-full">
              <h3 className="tw-text-white tw-text-[26px]">Sinopse:</h3>
              <hr className="tw-w-full tw-bg-lightPurple tw-h-[1px] tw-border-none tw-my-[10px]" />
              <p className="tw-text-lightPink">{movie.movie_data.synopsis}</p>
            </div>
            <div className="tw-grid tw-grid-cols-2 tw-mt-[30px] tw-gap-y-[30px]">
              <div className="tw-w-[90%]">
                <h3 className="tw-text-white tw-text-[26px]">Elenco:</h3>
                <hr className="tw-w-full tw-bg-lightPurple tw-h-[1px] tw-border-none tw-my-[10px]" />
                <p className="tw-text-lightPink">{movie.movie_data.cast}</p>
              </div>
              <div className="tw-w-[90%]">
                <h3 className="tw-text-white tw-text-[26px]">Prêmios:</h3>
                <hr className="tw-w-full tw-bg-lightPurple tw-h-[1px] tw-border-none tw-my-[10px]" />
                <p className="tw-text-lightPink">{movie.movie_data.awards}</p>
              </div>
              <div className="tw-w-[90%]">
                <h3 className="tw-text-white tw-text-[26px]">Diretor:</h3>
                <hr className="tw-w-full tw-bg-lightPurple tw-h-[1px] tw-border-none tw-my-[10px]" />
                <p className="tw-text-lightPink">{movie.movie_data.director}</p>
              </div>
              <div className="tw-w-[90%]">
                <h3 className="tw-text-white tw-text-[26px]">Avaliações:</h3>
                <hr className="tw-w-full tw-bg-lightPurple tw-h-[1px] tw-border-none tw-my-[10px]" />
                <p className="tw-text-lightPink">{movie.movie_data.rating}</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </main>
  );
}
