import Header from "../../components/ui/Header";
import Head from "next/head";

export default function Movies() {
  return (
    <main className="tw-bg-darkPurple tw-h-[100vh] tw-w-full">
      <Head>
        <title>Laon Productions - Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </main>
  );
}
