import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

//Components
import Header from "../components/ui/Header";
import api from "../services/api";

export async function getServerSideProps() {
  const movies = await api("/movie");

  return {
    props: {
      movies: movies.data,
    },
  };
}

export default function Home({ movies }) {
  console.log(movies);
  const router = useRouter();
  return (
    <div className="tw-bg-darkPurple tw-h-[100vh]">
      <Head>
        <title>Laon Productions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="tw-w-full tw-px-[5%] tw-mt-[30px]">
        <h1 className="tw-text-white tw-text-[40px] tw-mb-[30px]">POPULARES</h1>
        <div className="tw-w-full">
          <div className="tw-w-full tw-flex tw-justify-between">
            <h3 className="tw-text-lightPink tw-mb-[15px] tw-text-[18px]">
              FLMES
            </h3>
            <button
              onClick={() => router.push("movies")}
              className="tw-text-white tw-flex tw-items-center tw-cursor-pointer"
            >
              <div className="tw-border-[1px] tw-border-lightPurple tw-rounded-[50%] tw-p-[10px] tw-mr-[10px]">
                <img src="/icons/arrow.svg" className="tw-rotate-[180deg]" />
              </div>
            </button>
          </div>
          <div className="tw-flex">
            {movies.map((movie, i) => (
              <Link href={`/movies/${movie.slug}`} id="movie-card">
                <img
                  src={!!movie.cover_image && movie.cover_image}
                  className="tw-w-[180px] tw-h-[264px] tw-object-cover tw-mr-[20px]"
                />
              </Link>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
